version: '3'

services:
  web:
    restart: always
    build: ./porfolio
    ports:
      - "8005:8000"
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - ./porfolio:/application
      - web-static:/application/static
      - web-media:/application/media
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    # command: /usr/local/bin/gunicorn porfolio.wsgi:application -w 2 -b :8000
  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5435:5432"
    env_file: .postgres_env
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  web-media:
  web-django:
  web-static:
  pgdata:
  redisdata:
