version: '3'

services:
  web:
    restart: always
    build: ./porfolio
    ports:
      - "8000:8000"
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - ./data/static:/application/static
      - ./data/media:/application/media
    env_file: .env
    command: bash -c "/application/manage.py collectstatic --noinput;/usr/local/bin/gunicorn porfolio.wsgi:application -w 2 -b :8000"
    #command: /usr/local/bin/gunicorn docker_django.wsgi:application -w 2 -b :8000
volumes:
  web-media:
  web-static: