# Generated by Django 3.2.16 on 2022-12-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techblog', '0004_alter_blogpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='main_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Portada'),
        ),
    ]
