# Generated by Django 3.2.16 on 2022-12-24 18:24

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('techblog', '0006_alter_blogpage_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='extract',
            field=wagtail.fields.RichTextField(max_length=240, null=True, verbose_name='Extracto'),
        ),
    ]
