# Generated by Django 3.2.16 on 2022-12-25 16:00

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('techblog', '0009_alter_blogpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('quote', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('youtube_video', wagtail.blocks.URLBlock()), ('gallery', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(), icon='image', label='Gallery'))], use_json_field=True, verbose_name='Cuerpo de la publicación'),
        ),
    ]
