# Generated by Django 3.2.16 on 2022-12-25 17:46

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('techblog', '0010_alter_blogpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='techbloghome',
            name='carrousel',
            field=wagtail.fields.StreamField([('image', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock(max=3, min=1, page_type=['techblog.BlogPage']), icon='view', label='Gallery'))], null=True, use_json_field=True, verbose_name='Carrusel'),
        ),
    ]
