# Generated by Django 3.2.16 on 2022-12-25 17:50

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('techblog', '0011_techbloghome_carrousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techbloghome',
            name='carrousel',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock(max=3, min=1, page_type=['techblog.BlogPage']))], null=True, use_json_field=True, verbose_name='Carrusel'),
        ),
    ]
