# Generated by Django 3.2.16 on 2022-12-25 18:01

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('techblog', '0012_alter_techbloghome_carrousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='techbloghome',
            name='blog_index_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='techbloghome',
            name='blog_index_1_page_count',
            field=models.IntegerField(default=1, verbose_name='¿Cuantas páginas de esta sección se mostrarán?'),
        ),
        migrations.AlterField(
            model_name='techbloghome',
            name='carrousel',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock(page_type=['techblog.BlogPage']))], null=True, use_json_field=True, verbose_name='Carrusel'),
        ),
    ]
