# Generated by Django 3.2.16 on 2022-12-25 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('techblog', '0015_auto_20221225_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='techbloghome',
            name='blog_index_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='techbloghome',
            name='blog_index_4_page_count',
            field=models.IntegerField(default=1, verbose_name='¿Cuantas páginas de esta sección se mostrarán?'),
        ),
    ]
