# Generated by Django 3.2.16 on 2022-12-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20221223_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='footer_legend',
            field=models.CharField(default='Moisés Sepúlveda - Sitio construido utilizando DJANGO WAGTAIL', max_length=200, null=True, verbose_name='Mensaje del footer'),
        ),
    ]
