# Generated by Django 3.2.16 on 2022-12-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_footer_legend'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='tab_text',
            field=models.CharField(default='Ingresa el título de la pestaña', max_length=200, null=True, verbose_name='Texto de la pestaña'),
        ),
    ]
