# Generated by Django 3.2.13 on 2022-06-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplelist', '0002_auto_20220612_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplelistpage',
            name='download_caption',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Descripción descarga'),
        ),
    ]
