# Generated by Django 3.2.16 on 2022-12-23 23:41

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('simplelist', '0003_alter_simplelistpage_download_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersettings',
            name='footer_urls',
            field=wagtail.fields.StreamField([('url', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock(label='Etiqueta', max_length=50)), ('urls', wagtail.blocks.URLBlock(label='URL'))], label='URL'))], blank=True, default='', null=True, use_json_field=True),
        ),
    ]
