# Generated by Django 3.2.16 on 2022-12-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0006_serviceconsultingpage_side_block_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconsultingpage',
            name='contact_us_title',
            field=models.CharField(default='¿Tienes alguna duda?', max_length=30, verbose_name='Título de contactanos'),
        ),
    ]
