# Generated by Django 3.2.16 on 2022-12-29 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0007_serviceconsultingpage_contact_us_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceconsultingpage',
            name='description',
        ),
    ]
