# Generated by Django 3.2.16 on 2023-01-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0009_homeconsulting_hero_over_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeconsulting',
            name='hero_over_title',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='texto sobre titulo principal'),
        ),
    ]
