# Generated by Django 3.2.16 on 2023-01-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0010_alter_homeconsulting_hero_over_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeconsulting',
            name='hero_title_description',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='descripcion titulo principal'),
        ),
    ]
