# Generated by Django 3.2.16 on 2023-01-05 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('consulting', '0011_homeconsulting_hero_title_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeconsulting',
            name='button_redirect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homeconsulting',
            name='hero_button',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='texto boton'),
        ),
    ]
