# Generated by Django 3.2.16 on 2023-01-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0012_auto_20230104_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeconsulting',
            old_name='button_redirect',
            new_name='hero_button_title_redirect',
        ),
        migrations.RemoveField(
            model_name='homeconsulting',
            name='hero_button',
        ),
        migrations.AddField(
            model_name='homeconsulting',
            name='hero_button_title',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='texto boton titulo'),
        ),
        migrations.AlterField(
            model_name='homeconsulting',
            name='hero_title_description',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='descripcion titulo principal'),
        ),
    ]
