# Generated by Django 3.2.16 on 2023-01-05 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0012_auto_20230105_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formpage',
            name='form_title',
        ),
    ]
