# Generated by Django 3.2.16 on 2023-01-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0013_auto_20230104_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeconsulting',
            name='hero_agile_develop',
            field=models.CharField(default='item 1', max_length=50, verbose_name='item descripción 1'),
        ),
        migrations.AddField(
            model_name='homeconsulting',
            name='hero_information_security',
            field=models.CharField(default='item 2', max_length=50, verbose_name='item descripción 2'),
        ),
        migrations.AddField(
            model_name='homeconsulting',
            name='hero_scalabiliti',
            field=models.CharField(default='item 3', max_length=50, verbose_name='item descripción 3'),
        ),
    ]
