# Generated by Django 3.2.16 on 2023-01-05 02:11

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0013_remove_formpage_form_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='success_message_desc',
            field=wagtail.fields.RichTextField(default='', verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='success_message_title',
            field=models.CharField(default='Información recibida correctamente', max_length=100, verbose_name='Mensaje de éxito'),
        ),
    ]
