# Generated by Django 3.2.16 on 2023-01-05 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0014_auto_20230104_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeconsulting',
            old_name='hero_scalabiliti',
            new_name='hero_scalability',
        ),
        migrations.AddField(
            model_name='homeconsulting',
            name='hero_agile_develop_desc',
            field=models.CharField(default='item 1.1', max_length=50, verbose_name='item descripción 1.1'),
        ),
        migrations.AddField(
            model_name='homeconsulting',
            name='hero_information_security_desc',
            field=models.CharField(default='item 2.1', max_length=50, verbose_name='item descripción 2.1'),
        ),
        migrations.AddField(
            model_name='homeconsulting',
            name='hero_scalability_desc',
            field=models.CharField(default='item 3.1', max_length=50, verbose_name='item descripción 3.1'),
        ),
    ]
