# Generated by Django 3.2.16 on 2023-01-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0016_auto_20230104_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeconsulting',
            name='hero_agile_develop',
            field=models.CharField(default='item 1', max_length=50, verbose_name='item 1 titulo'),
        ),
        migrations.AlterField(
            model_name='homeconsulting',
            name='hero_agile_develop_desc',
            field=models.CharField(default='', max_length=150, verbose_name='item descripción 1'),
        ),
        migrations.AlterField(
            model_name='homeconsulting',
            name='hero_information_security',
            field=models.CharField(default='item 2', max_length=50, verbose_name='item 2 titulo'),
        ),
        migrations.AlterField(
            model_name='homeconsulting',
            name='hero_information_security_desc',
            field=models.CharField(default='', max_length=150, verbose_name='item descripción 2'),
        ),
        migrations.AlterField(
            model_name='homeconsulting',
            name='hero_scalability',
            field=models.CharField(default='item 3', max_length=50, verbose_name='item 3 titulo'),
        ),
        migrations.AlterField(
            model_name='homeconsulting',
            name='hero_scalability_desc',
            field=models.CharField(default='', max_length=150, verbose_name='item descripción 3'),
        ),
    ]
