# Generated by Django 3.2.16 on 2023-01-05 04:10

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('consulting', '0016_formpage_bottom_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('h1', wagtail.blocks.CharBlock(form_classname='title')), ('h2', wagtail.blocks.CharBlock(form_classname='title')), ('h3', wagtail.blocks.CharBlock(form_classname='title')), ('h4', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('quote', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('youtube_video', wagtail.blocks.URLBlock()), ('gallery', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(), icon='image', label='Gallery'))], blank=True, null=True, use_json_field=True, verbose_name='Cuerpo de la página')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='bottom_body',
            field=wagtail.fields.StreamField([('h1', wagtail.blocks.CharBlock(form_classname='title')), ('h2', wagtail.blocks.CharBlock(form_classname='title')), ('h3', wagtail.blocks.CharBlock(form_classname='title')), ('h4', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('quote', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('youtube_video', wagtail.blocks.URLBlock()), ('gallery', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(), icon='image', label='Gallery'))], blank=True, null=True, use_json_field=True, verbose_name='Cuerpo debaje del formulario'),
        ),
    ]
