# Generated by Django 3.2.16 on 2023-01-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0017_auto_20230104_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeconsulting',
            name='hero_our_company',
            field=models.CharField(default='nuestra compañia', max_length=100, verbose_name='nuestra compañia'),
        ),
        migrations.AddField(
            model_name='homeconsulting',
            name='hero_our_company_desc',
            field=models.CharField(default='nuestra compañia descripción', max_length=100, verbose_name='nuestra compañia descripción'),
        ),
    ]
