# Generated by Django 3.2.16 on 2023-01-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0018_auto_20230104_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeconsulting',
            name='hero_our_company_desc',
            field=models.CharField(default='nuestra compañia descripción', max_length=200, verbose_name='nuestra compañia descripción'),
        ),
    ]
