# Generated by Django 3.2.16 on 2023-01-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0019_alter_homeconsulting_hero_our_company_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeconsulting',
            name='hero_company_customer',
            field=models.CharField(default='customer review', max_length=100, verbose_name='titulo customer review'),
        ),
        migrations.AddField(
            model_name='homeconsulting',
            name='hero_company_customer_desc',
            field=models.CharField(default='nuestra compañia descripción', max_length=200, verbose_name='customer review descripción'),
        ),
        migrations.AddField(
            model_name='homeconsulting',
            name='hero_company_success',
            field=models.CharField(default='success project', max_length=100, verbose_name='titulo success project'),
        ),
        migrations.AddField(
            model_name='homeconsulting',
            name='hero_company_success_desc',
            field=models.CharField(default='nuestra compañia descripción', max_length=200, verbose_name='success project descripción'),
        ),
        migrations.AddField(
            model_name='homeconsulting',
            name='hero_title_company',
            field=models.CharField(default='nuestra compañia titulo', max_length=100, verbose_name='nuestra compañia titulo'),
        ),
    ]
