# Generated by Django 3.2.16 on 2023-01-05 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('consulting', '0021_auto_20230105_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeconsulting',
            name='hero_button_service',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='texto boton service'),
        ),
        migrations.AddField(
            model_name='homeconsulting',
            name='hero_button_services_redirect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
