# Generated by Django 3.2.16 on 2023-01-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0022_auto_20230105_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeconsulting',
            name='hero_process_desc',
            field=models.CharField(default='', max_length=100, verbose_name='proceso descripción'),
        ),
        migrations.AddField(
            model_name='homeconsulting',
            name='hero_process_title',
            field=models.CharField(default='', max_length=100, verbose_name='titulo procesos'),
        ),
    ]
