# Generated by Django 3.2.16 on 2023-01-05 04:06

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0025_alter_homeconsulting_hero_process_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeconsulting',
            name='hero_process_step',
            field=wagtail.fields.StreamField([('card', wagtail.blocks.StructBlock([('title', wagtail.blocks.TextBlock(label='titulo')), ('subtitle', wagtail.blocks.TextBlock(label='subtitulo')), ('description', wagtail.blocks.RichTextBlock(label='descripcion'))]))], null=True, use_json_field=True),
        ),
    ]
