# Generated by Django 3.2.16 on 2023-01-06 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0017_auto_20230105_0410'),
        ('consulting', '0026_alter_homeconsulting_hero_process_step'),
    ]

    operations = [
    ]
