# Generated by Django 3.2.16 on 2023-01-06 01:02

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0027_merge_20230106_0048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formpage',
            options={'verbose_name': 'Página con formulario'},
        ),
        migrations.AlterModelOptions(
            name='infopage',
            options={'verbose_name': 'Página de información'},
        ),
        migrations.AlterModelOptions(
            name='serviceconsultingpage',
            options={'verbose_name': 'Página de servicio'},
        ),
        migrations.AlterField(
            model_name='formpage',
            name='body',
            field=wagtail.fields.StreamField([('h1', wagtail.blocks.CharBlock(form_classname='title')), ('h2', wagtail.blocks.CharBlock(form_classname='title')), ('h3', wagtail.blocks.CharBlock(form_classname='title')), ('h4', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock(label='Parrafo')), ('quote', wagtail.blocks.RichTextBlock(label='Cita')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Imagén')), ('youtube_video', wagtail.blocks.URLBlock(label='Video en youtube')), ('gallery', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(), icon='image', label='Galería'))], null=True, use_json_field=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='bottom_body',
            field=wagtail.fields.StreamField([('h1', wagtail.blocks.CharBlock(form_classname='title')), ('h2', wagtail.blocks.CharBlock(form_classname='title')), ('h3', wagtail.blocks.CharBlock(form_classname='title')), ('h4', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock(label='Parrafo')), ('quote', wagtail.blocks.RichTextBlock(label='Cita')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Imagén')), ('youtube_video', wagtail.blocks.URLBlock(label='Video en youtube')), ('gallery', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(), icon='image', label='Galería'))], blank=True, null=True, use_json_field=True, verbose_name='Cuerpo debaje del formulario'),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='success_body',
            field=wagtail.fields.StreamField([('h1', wagtail.blocks.CharBlock(form_classname='title')), ('h2', wagtail.blocks.CharBlock(form_classname='title')), ('h3', wagtail.blocks.CharBlock(form_classname='title')), ('h4', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock(label='Parrafo')), ('quote', wagtail.blocks.RichTextBlock(label='Cita')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Imagén')), ('youtube_video', wagtail.blocks.URLBlock(label='Video en youtube')), ('gallery', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(), icon='image', label='Galería'))], null=True, use_json_field=True, verbose_name='Cuerpo de la página de éxito'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='body',
            field=wagtail.fields.StreamField([('h1', wagtail.blocks.CharBlock(form_classname='title')), ('h2', wagtail.blocks.CharBlock(form_classname='title')), ('h3', wagtail.blocks.CharBlock(form_classname='title')), ('h4', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock(label='Parrafo')), ('quote', wagtail.blocks.RichTextBlock(label='Cita')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Imagén')), ('youtube_video', wagtail.blocks.URLBlock(label='Video en youtube')), ('gallery', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(), icon='image', label='Galería'))], blank=True, null=True, use_json_field=True, verbose_name='Cuerpo de la página'),
        ),
        migrations.AlterField(
            model_name='serviceconsultingpage',
            name='body',
            field=wagtail.fields.StreamField([('h1', wagtail.blocks.CharBlock(form_classname='title')), ('h2', wagtail.blocks.CharBlock(form_classname='title')), ('h3', wagtail.blocks.CharBlock(form_classname='title')), ('h4', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock(label='Parrafo')), ('quote', wagtail.blocks.RichTextBlock(label='Cita')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Imagén')), ('youtube_video', wagtail.blocks.URLBlock(label='Video en youtube')), ('gallery', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(), icon='image', label='Galería'))], null=True, use_json_field=True, verbose_name='Descripción del servicio'),
        ),
    ]
