# Generated by Django 3.2.16 on 2023-01-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0028_auto_20230106_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('text', models.CharField(max_length=255)),
            ],
        ),
    ]
