# Generated by Django 3.2.16 on 2023-01-13 19:55

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0029_auto_20230113_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeconsulting',
            name='hero_team_members',
            field=wagtail.fields.StreamField([('card', wagtail.blocks.StructBlock([('title', wagtail.blocks.TextBlock(label='titulo')), ('subtitle', wagtail.blocks.TextBlock(label='subtitulo')), ('description', wagtail.blocks.RichTextBlock(label='descripcion'))]))], null=True, use_json_field=True),
        ),
    ]
