# Generated by Django 3.2.16 on 2023-01-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0030_homeconsulting_hero_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeconsulting',
            name='hero_team',
        ),
        migrations.AddField(
            model_name='homeconsulting',
            name='hero_team_desc',
            field=models.CharField(default='', max_length=100, verbose_name='nuestro equipo descripción'),
        ),
        migrations.AddField(
            model_name='homeconsulting',
            name='hero_testimonials',
            field=models.CharField(default='', max_length=100, verbose_name='titulo testimonios'),
        ),
        migrations.AddField(
            model_name='homeconsulting',
            name='hero_testimonials_desc',
            field=models.CharField(default='', max_length=100, verbose_name='testimonios descripción'),
        ),
        migrations.AlterField(
            model_name='homeconsulting',
            name='hero_team_title',
            field=models.CharField(default='', max_length=100, verbose_name='titulo nuestro equipo'),
        ),
    ]
