# Generated by Django 3.2.16 on 2023-01-22 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0032_homeconsulting_hero_testimonias_cards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeconsulting',
            old_name='hero_testimonias_cards',
            new_name='hero_testimonials_cards',
        ),
    ]
