# Generated by Django 3.2.16 on 2023-01-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0034_auto_20230122_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeconsulting',
            name='hero_footer_company_desc',
            field=models.CharField(default='', max_length=300, verbose_name='descripcion empresa'),
        ),
        migrations.AlterField(
            model_name='homeconsulting',
            name='hero_footer_company_name',
            field=models.CharField(default='', max_length=100, verbose_name='nombre empresa'),
        ),
    ]
