# Generated by Django 3.2.16 on 2023-03-27 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0029_footer'),
        ('consulting', '0035_auto_20230122_1355'),
    ]

    operations = [
    ]
