# Generated by Django 3.2.16 on 2023-03-28 00:02

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('wagtailimages', '0024_index_image_file_hash'),
        ('consulting', '0036_merge_0029_footer_0035_auto_20230122_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_name', models.TextField(max_length=100, verbose_name='Nombre de la empresa')),
                ('contact_phone', models.TextField(max_length=100, verbose_name='Teléfono de contacto')),
                ('contact_email', models.EmailField(max_length=255, verbose_name='Correo de contacto')),
                ('facebook_link', models.URLField(blank=True, null=True, verbose_name='Enlace a facebook')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='Enlace a instagram')),
                ('twitter_link', models.URLField(blank=True, null=True, verbose_name='Enlace a twitter')),
                ('linkedin_link', models.URLField(blank=True, null=True, verbose_name='Enlace a linked in')),
                ('footer_urls', wagtail.fields.StreamField([('url', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock(label='Etiqueta', max_length=50)), ('urls', wagtail.blocks.URLBlock(label='URL'))], label='URL'))], blank=True, default='', null=True, use_json_field=True)),
                ('contact_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('enterprise_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo de la empresa')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Configuración general página',
            },
        ),
    ]
