# Generated by Django 3.2.16 on 2023-03-28 00:05

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('consulting', '0037_generalinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='contact_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Página de contacto'),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='footer_urls',
            field=wagtail.fields.StreamField([('url', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock(label='Etiqueta', max_length=50)), ('urls', wagtail.blocks.PageChooserBlock(label='URL'))], label='URL'))], blank=True, default='', null=True, use_json_field=True),
        ),
    ]
