# Generated by Django 3.2.16 on 2023-03-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0039_auto_20230328_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinfo',
            name='footer_resume',
            field=models.TextField(blank=True, null=True, verbose_name='Reseña al pie de página'),
        ),
    ]
