# Generated by Django 3.2.16 on 2023-03-28 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('consulting', '0040_generalinfo_footer_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinfo',
            name='privacy_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Página de privacidad'),
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='terms_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Página de términos y condiciones'),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='contact_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Página de contacto'),
        ),
    ]
