# Generated by Django 3.2.16 on 2023-03-28 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('consulting', '0041_auto_20230328_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinfo',
            name='home_page',
            field=models.ForeignKey(blank=True, help_text='¿Cual será la página principal del sitio?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Página de inicio'),
        ),
    ]
