# Generated by Django 3.2.16 on 2023-03-28 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0042_generalinfo_home_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeconsulting',
            name='hero_footer_company_desc',
        ),
        migrations.RemoveField(
            model_name='homeconsulting',
            name='hero_footer_company_name',
        ),
        migrations.RemoveField(
            model_name='homeconsulting',
            name='hero_footer_privacy_policy',
        ),
        migrations.RemoveField(
            model_name='homeconsulting',
            name='hero_footer_terms_conditions',
        ),
        migrations.RemoveField(
            model_name='homeconsulting',
            name='hero_footer_year',
        ),
    ]
