# Generated by Django 3.2.16 on 2023-03-31 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('consulting', '0043_auto_20230328_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinfo',
            name='enterprise_logo_footer',
            field=models.ForeignKey(blank=True, help_text='Este logo aparecerá en el pie de página de todo el sitio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo de la empresa en el pie de página'),
        ),
    ]
