# Generated by Django 3.2.16 on 2023-04-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0044_generalinfo_enterprise_logo_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinfo',
            name='whatsapp_number',
            field=models.TextField(blank=True, null=True, verbose_name='Número de Whatsapp'),
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='whatsapp_text',
            field=models.TextField(blank=True, null=True, verbose_name='Texto whatsapp'),
        ),
    ]
