# Generated by Django 3.2.16 on 2023-04-06 01:03

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0046_auto_20230404_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeconsulting',
            name='hero_testimonials_cards',
            field=wagtail.fields.StreamField([('card', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(label='Imagen')), ('name', wagtail.blocks.TextBlock(label='nombre')), ('position', wagtail.blocks.TextBlock(label='cargo')), ('description', wagtail.blocks.RichTextBlock(label='descripcion'))]))], null=True, use_json_field=True),
        ),
    ]
