# Generated by Django 3.2.16 on 2023-04-06 01:04

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0047_alter_homeconsulting_hero_testimonials_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeconsulting',
            name='hero_team_members',
            field=wagtail.fields.StreamField([('card', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(label='Imagen')), ('title', wagtail.blocks.TextBlock(label='titulo')), ('subtitle', wagtail.blocks.TextBlock(label='subtitulo')), ('description', wagtail.blocks.RichTextBlock(label='descripcion'))]))], null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='homeconsulting',
            name='hero_testimonials_cards',
            field=wagtail.fields.StreamField([('card', wagtail.blocks.StructBlock([('name', wagtail.blocks.TextBlock(label='nombre')), ('position', wagtail.blocks.TextBlock(label='cargo')), ('description', wagtail.blocks.RichTextBlock(label='descripcion'))]))], null=True, use_json_field=True),
        ),
    ]
