# Generated by Django 3.2.16 on 2023-04-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0051_auto_20230415_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo Contrato',
                'verbose_name_plural': 'Tipo contratos',
            },
        ),
    ]
