# Generated by Django 3.2.16 on 2023-04-15 16:10

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0052_contracttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='consulting.contracttype')),
                ('employee', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='consulting.employee')),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='consulting.jobposition')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
