# Generated by Django 3.2.16 on 2023-04-15 16:17

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0053_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='consulting.contracttype', verbose_name='Tipo de contrato'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de termino'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_start',
            field=models.DateField(verbose_name='Fecha inicio'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='job_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='consulting.jobposition', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Remuneración'),
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Monto')),
                ('date', models.DateField(verbose_name='Fecha pago')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='glosa')),
                ('employee', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='consulting.employee')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
