# Generated by Django 3.2.16 on 2023-04-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0054_auto_20230415_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='carrer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='university',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
