# Generated by Django 3.2.16 on 2023-04-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0055_auto_20230415_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='enterprise_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo corporativo'),
        ),
        migrations.AddField(
            model_name='employee',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo personal'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='carrer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='university',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Universidad/Instituto'),
        ),
    ]
