# Generated by Django 3.2.16 on 2023-09-19 23:09

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0057_alter_employee_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeconsulting',
            name='hero_team_desc',
        ),
        migrations.RemoveField(
            model_name='homeconsulting',
            name='hero_team_members',
        ),
        migrations.RemoveField(
            model_name='homeconsulting',
            name='hero_team_title',
        ),
        migrations.AddField(
            model_name='homeconsulting',
            name='hero_clients_desc',
            field=models.CharField(default='', max_length=100, verbose_name='que han confiado en nosotros'),
        ),
        migrations.AddField(
            model_name='homeconsulting',
            name='hero_clients_members',
            field=wagtail.fields.StreamField([('card', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(label='Imagen')), ('title', wagtail.blocks.TextBlock(label='titulo'))]))], null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='homeconsulting',
            name='hero_clients_title',
            field=models.CharField(default='', max_length=100, verbose_name='Nuestros clientes'),
        ),
    ]
